### ISSUE TITLE
Still Running

### ISSUE THREAD

**Issue by jtwebman** [mafintosh/why-is-node-running#1]
Node stays running because you have 2 setIntervals callbacks running every second. You will need to call clearInterval with the value returned from the setInterval to stop them. 

You also have two net servers listen on port 0 which means the server will pick a random port to listen on. They will listen forever so you will need to call server.close(*cb) if you want the node process to stop.

**Comment by freeall** [comment]
Perfect answer!

**Comment by ralphtheninja** [comment]
:grinning:

**Comment by jtwebman** [comment]
Now if we can change the tool to say this it woukd be even better. :)

**Comment by jonkoops** [comment]
Hahahah, thanks for the laugh.

**Comment by jtwebman** [comment]
I forgot about this now that Node has these tools built in it is much easier to figure this out.

**Comment by jonkoops** [comment]
> I forgot about this now that Node has these tools built in it is much easier to figure this out.

Which tools are you referring to @jtwebman?

**Comment by jtwebman** [comment]
@jonkoops https://nodejs.org/api/async_context.html#asynchronous-context-tracking

**Comment by jonkoops** [comment]
Nice, thanks for that information. From looking at the docs that is the API that is supposed to replace `async_hooks`, we're tracking that under #64 so we'll get to evaluating how feasible that is soon enough.
