### ISSUE TITLE
TypeError: self._handle.connect is not a function

### ISSUE THREAD

**Issue by mooyoul** [mafintosh/why-is-node-running#12]
<img width="589" alt="2016-04-07 11 22 05" src="https://cloud.githubusercontent.com/assets/2101743/14354361/f6bfe116-fd17-11e5-8a5c-67d1b59d75af.png">

Something went wrong on `net` module binding when using `why-is-node-running` with request+bluebird combo.

I got this error:

```
net.js:822
      err = self._handle.connect(req, address, port);
                         ^

TypeError: self._handle.connect is not a function
    at connect (net.js:822:26)
    at net.js:984:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```

I tried to find the reason why it is fails, but i could't find.

This is test code which i used.

``` javascript
'use strict';

/**
 * Module dependencies.
 */
const why         = require('why-is-node-running');

const
  Promise     = require('bluebird'),
  request     = require('request');


const
  feeds = [
    'http://www.gojobs.go.kr/employ/rss.asp',
    'https://github.com/mooyoul.atom',
    'https://github.com/Flexget/Flexget/commits/develop.atom'
  ];

const fetch = (url) => {
  return new Promise((resolve, reject) => {
    request({
      method: 'GET',
      url: url
    }, (e, res, body) => {
      if (e) {
        return reject(e);
      }

      resolve(body);
    });
  });
};

Promise.map(feeds, (feed, index) => {
  console.log('fetching feed index %d: %s', index, feed);
  return fetch(feed);
});
```

**Comment by mooyoul** [comment]
Just to clarify, I tested some tests.
It seems related to `request` module.
(not related to ES6 arrow function feature and `bluebird` package)


If i call `request` over once, it fails. calling `request` once is okay.

This is another test example:
```javsacript
'use strict';

/**
 * Module dependencies.
 */
const why         = require('why-is-node-running');

const
  request     = require('request');

request({
  method: 'GET',
  url: 'http://www.gojobs.go.kr/employ/rss.asp'
}, function (e, r, body) {
  request({
    method: 'GET',
    url: 'https://github.com/mooyoul.atom'
  }, function (e, r, body) {
  });
});
```

**Comment by yoshuawuyts** [comment]
Can confirm, have run into this before too (no repro available tho, was in a rush).

**Comment by nolanlawson** [comment]
Ran into this as well. Can confirm that the above test cases repros the failure, using Yosemite, request@2.72.0, and why-is-node-running@1.2.2.

**Comment by atrhacker** [comment]
Hey, I have the same issue. 
So sad, because this tool seems perfect to diagnose my issue.
Is there any alternative ?

Thanks

**Comment by mafintosh** [comment]
I'll try to find some time over the weekend to fix this. Thanks for reporting it 👍

**Comment by forivall** [comment]
I ran into this issue too, but https://github.com/myndzi/wtfnode was able to work.

**Comment by sibelius** [comment]
using `why-is-node-running` as cli does the same result

**Comment by mafintosh** [comment]
Should be fixed in latest

**Comment by mooyoul** [comment]
Ooh finally! Thanks :)
