### ISSUE TITLE
eval'ed code will fail.

### ISSUE THREAD

**Issue by rhalff** [mafintosh/why-is-node-running#16]
I've tried to use `why-is-node-running` with code using `Promise.promisifyAll()` from bluebird and it failed because it uses `eval()` or `new Function` at least.

The following piece of code will trigger the bug:

_test.js_:

``` javascript
var log = require('why-is-node-running')

eval('console.log("fail")')

log()
```

_result:_

``` javascript
$ node --expose-internals test.js
bug-why/node_modules/why-is-node-running/index.js:73
      return s.getFileName().indexOf(require('path').sep) > -1
```

Part of the code which is failing:
https://github.com/mafintosh/why-is-node-running/blob/a0268be/index.js#L73-L90

It could be solved by using `s.isEval()` and `s.getEvalOrigin()` from callsite-object.

See:  https://github.com/defunctzombie/node-stackback#callsite-object

**Comment by mafintosh** [comment]
This this works in latest. If not please reopen :)
