### ISSUE TITLE
Requirements and impact

### ISSUE THREAD

**Issue by julien-f** [mafintosh/why-is-node-running#2]
Is there a minimal Node version requirement for this module?

Is there any performance impact due to the use of this module?

Should it be used in production?

**Comment by mafintosh** [comment]
the perf impact is minor since its only instrumenting the handle creations in node. i haven't tested this on old node versions (<= 0.12) it would probably be easy to get it to work there if it doesn't

**Comment by mafintosh** [comment]
i'd use it in production myself if i had a weird bug in regards to something keeping the event loop running.

**Comment by julien-f** [comment]
Ok, thanks for the info, they could be in the README though :)
