### ISSUE TITLE
Unknown handles?

### ISSUE THREAD

**Issue by darkpixel** [mafintosh/why-is-node-running#20]
I'm at a loss as to why my app isn't closing.  I get the following output:
```
There are 0 known handle(s) keeping the process running and 4 unknown
Known handles:

^C
#
```

What are 'unknown' handles?

**Comment by megakoresh** [comment]
Yeah same here, trying to debug gulp task - 3 unknown handles. I think this package is abandoned and not maintained, need to find an alternative.

**Comment by darkpixel** [comment]
Awesome!  Thanks @yoshuawuyts!
