### ISSUE TITLE
Workaround for `Cannot find module 'internal/linkedlist'`

### ISSUE THREAD

**Issue by allenluce** [mafintosh/why-is-node-running#26]
Until it's addressed, try https://github.com/myndzi/wtfnode instead.

(This was [mentioned in a prior issue](https://github.com/mafintosh/why-is-node-running/issues/12#issuecomment-251269489) but deserves a little more exposure.)

**Comment by andreyrd** [comment]
This error happens if you run `why-is-node-running` without the `--expose-internals` flag.
That said, thanks for pointing out `wtfnode`, I needed an alternative because of #19 :)

**Comment by GuyMograbi** [comment]
This seems like an awesome tool. Can't wait to see it work. 
I ran into this issue and adding the flag did not solve it to me.

**Comment by jeffvandyke** [comment]
```
node --expose-internals ./node_modules/.bin/_mocha
```
discovered at the top of <https://github.com/mochajs/mocha/issues/3045>, YMMV

**Comment by emilioplatzer** [comment]
But...
```sh
c:\my-path\my-repo\node_modules\.bin\_mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

**Comment by mafintosh** [comment]
should be fixed in latest
