### ISSUE TITLE
Usage with mocha

### ISSUE THREAD

**Issue by mpelzsherman** [mafintosh/why-is-node-running#27]
I am trying to use this tool to figure out why my mocha tests are hanging, as [recommended](https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit).

Our project has the following script defined in `package.json`:

```javascript
    "test": "NODE_ENV=test NODE_PATH=./src:./test mocha src/**/__tests__/**/*.js",
```
We typically use the command `yarn test` to run our tests.

What command should I use to run our tests under this tool? When I do this:

`$ why-is-node-running yarn test`

I get:

```
Error: Cannot find module '/Users/mpelzsherman/source/ag.js/yarn'
```

Many thanks!

**Comment by ralphtheninja** [comment]
I would skip `yarn` and try going directly to the test command `NODE_ENV=test NODE_PATH=./src:./test why-is-node-running ./node_modules/.bin/mocha src/**/__tests__/**/*.js`.

You should be able to wrap this as well, e.g.

```
  "testwhy": "NODE_ENV=test NODE_PATH=./src:./test why-is-node-running ./node_modules/.bin/mocha src/**/__tests__/**/*.js",
```

**Comment by mpelzsherman** [comment]
Thanks @ralphtheninja ! 

I ended up using [wtfnode](https://github.com/myndzi/wtfnode) instead, with the following command:

export NODE_ENV=test
export NODE_PATH=./src:./test
wtfnode ~/source/ag.js/node_modules/mocha/bin/_mocha --compilers js:babel-core/register --timeout 5000 --require ./test/setup.js src/**/__tests__/**/*.js
