### ISSUE TITLE
I need to figure out why an aws lambda is hanging

### ISSUE THREAD

**Issue by justinmchase** [mafintosh/why-is-node-running#28]
I can't add the flag `--expose-internals` to the call, is there any other way I can figure out what is hanging open?

**Comment by yoshuawuyts** [comment]
@justinmchase you could try and spawn a child process from lambda, like we're doing here https://github.com/mafintosh/why-is-node-running/blob/master/cli.js

If that doesn't work, it might get tricky. Lambda was designed as a black box, so it, yeah, it's sort of intentionally meant to not be debugged in this way I guess.

**Comment by justinmchase** [comment]
@yoshuawuyts Thanks.

In case anyone comes here asking similar questions in the future, after finally digging deep enough through the docs, I found this which solved the issue for me finally:

[callbackWaitsForEmptyEventLoop](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html)
> The default value is true. This property is useful only to modify the default behavior of the callback. By default, the callback will wait until the Node.js runtime event loop is empty before freezing the process and returning the results to the caller. You can set this property to false to request AWS Lambda to freeze the process soon after the callback is called, even if there are events in the event loop. AWS Lambda will freeze the process, any state data and the events in the Node.js event loop (any remaining events in the event loop processed when the Lambda function is called next and if AWS Lambda chooses to use the frozen process). For more information about callback, see Using the Callback Parameter.

For my case simply setting this to false early in my lambda allowed it to actually close without hanging when I called the callback:
```
context.callbackWaitsForEmptyEventLoop = false
example() // function that hangs open a socket or fd
callback() // will now call process.exit() for you safely
```


Obviously closing all of your unmanaged resources properly is the ideal way to solve this issue but this is a pretty effective sledgehammer approach when that becomes tricky.

**Comment by yoshuawuyts** [comment]
@justinmchase glad you figured it out! Thanks for the detailed response! :sparkles:

**Comment by skylarmb** [comment]
@justinmchase Thank you! `context.callbackWaitsForEmptyEventLoop` was the culprit for me as well.

**Comment by AvitureArt** [comment]
@justinmchase You are my hero.

**Comment by SET001** [comment]
in my case I was using [sequelize](https://github.com/sequelize/sequelize) orm and I have to call `await sequelize.close() ` at the end of each lambda. Setting `context.callbackWaitsForEmptyEventLoop` to `false` does not help in my case.

**Comment by Lan19094** [comment]
Thanks for saving my career :D
