### ISSUE TITLE
`filename` is null, cannot read .indexOf of null

### ISSUE THREAD

**Issue by catcher-in-the-try** [mafintosh/why-is-node-running#30]
Change this line:

`return  filename.indexOf(sep) > -1 && filename.indexOf('internal' + sep) !== 0`

to

`return filename && filename.indexOf(sep) > -1 && filename.indexOf('internal' + sep) !== 0`

Somehow the filename is null on my Node 8.9

**Comment by mafintosh** [comment]
Mind sending a PR?

**Comment by mafintosh** [comment]
fixed by you in latest \o/
