### ISSUE TITLE
This could lead to memory leak of Promise/PromiseWrap

### ISSUE THREAD

**Issue by strawhatboy** [mafintosh/why-is-node-running#35]
Hello guys,

I was using this module to track what is pending in my nodejs project, and once my node process ended with __heap out of memory__, I was confused a lot by checking my code for memory leak...

Finally with ChromeDev tools, I found that the objects Array, Promise & PromiseWrap were always increasing without being released by GC, and they're somehow related to this module.

By checking the source code, `async-hook` was used to track all the Promises/async/await, and they're put into a map... so I think that's where the leak happens. and after removed `require('why-is-node-running')` from my code, the memory leak was gone.

So maybe I would like to recommend to put some __WARNINGS__ in the `README.md` file of this module like:
if you're __creating new `Promises` to wrap traditional callbacks a lot__, this module could lead to __memory leaks__...

Thanks.

**Comment by mafintosh** [comment]
should be fixed by #37

**Comment by cardin** [comment]
I'm writing a site cloner where I'm encountering a scenario with 60,000+ TLSWrap and ZLIB handlers reported. I definitely do not have that many open connections.

For larger sites, I get OOM failure. I tried removing `why-is-node-running` and the OOM went away.

Could the OOM issue be related to this? https://github.com/nodejs/node/issues/33468 I'm running Node 12.8.2.
