### ISSUE TITLE
Why all promises ever performed are reported

### ISSUE THREAD

**Issue by imrefazekas** [mafintosh/why-is-node-running#39]
I'm having hard time with this lib.
It reports all promises the running app ever performed.

hashtab PROMISE
/.../node_modules/mongodb/lib/utils.js:432                   - return new Promise(function(resolve, reject) {

All promises performed by any libraries. Mongodb driver or actually anything.
Even is the app shuts down clearly, it says:
There are 10272 handle(s) keeping the process running

Is there a way to learn why async / await promises give such a headache to this lib?

**Comment by mafintosh** [comment]
fixed by #37
