### ISSUE TITLE
We need types definitions for typescript support

### ISSUE THREAD

**Issue by zlydenko** [mafintosh/why-is-node-running#48]

**Comment by jswalden** [comment]
You can work around this by putting a `why-is-node-running.d.ts` file within your project, in a place where your `tsconfig.json` will instruct that it be compiled, and fill it with these contents:

```typescript
interface WithConsoleErrorStyleMethod {
	error: Console['error']
}

declare module 'why-is-node-running' {
	export default function log(logger?: WithConsoleErrorStyleMethod): void
}
```

Then `import whyIsNodeRunning from 'why-is-node-running'` and do `whyIsNodeRunning()` to trigger the dumping using `console.error` -- or pass your own object with a `'error'` property that behaves like `console.error` does, if you want to do something cuter.
