### ISSUE TITLE
Support for use directly through command line with `npx`

### ISSUE THREAD

**Issue by rbelling** [mafintosh/why-is-node-running#54]
It would be really nice if this tool offered a CLI interface that can be used with `npx why-is-node-running`. Any plans of adding that interface @mafintosh ? I can help!

**Comment by benadamstyles** [comment]
`npx why-is-node-running path/to/file.js` works fine for me!

**Comment by Maxim-Mazurok** [comment]
Yeah, `npx` should work, and docs can probably be updated to mention `npx` https://github.com/mafintosh/why-is-node-running#require-cli-option
