### ISSUE TITLE
Lots of RANDOMBYTESREQUEST handles of crypto since ~ node 15

### ISSUE THREAD

**Issue by SanderDeWaal1992** [mafintosh/why-is-node-running#57]
I used why-is-not-running in node 12 with much satisfaction but now I've upgraded to the node 16 LTS it is not working anymore for my use-case.

The native Node crypto module now gives a lot of RANDOMBYTESREQUEST  false positives. 

I think this is related to an issue on Jest: https://github.com/facebook/jest/issues/11275. Their fix: https://github.com/facebook/jest/pull/11278/files

**Comment by mafintosh** [comment]
Nice, good catch. I tried to push a fix, can you test it?

**Comment by SanderDeWaal1992** [comment]
Great, works perfect!
