### ISSUE TITLE
Cannot find module 'internal/linkedlist'

### ISSUE THREAD

**Issue by stefanjudis** [mafintosh/why-is-node-running#7]
Heyo, I just wanted to play around with this to see how it works.
Apparently I don't get it to work. :(

I've got a simple `index.js`.

```
var log = require('why-is-node-running') // should be your first require

log();
```

And `why-is-node-running` is available installed in my `node_modules`.

That's what I got:

```
stefan @ stefan-mac: ~/Downloads/test
> node --version
v5.0.0

stefan @ stefan-mac: ~/Downloads/test
> node ./index.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'internal/linkedlist'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at timers.js:4:11
    at NativeModule.compile (/Users/stefan/Downloads/test/node_modules/why-is-node-running/core.js:108:3)
    at Function.NativeModule.require (/Users/stefan/Downloads/test/node_modules/why-is-node-running/core.js:52:16)
    at Object.globalTimeouts (/Users/stefan/Downloads/test/node_modules/why-is-node-running/core.js:14:31)
    at Object.<anonymous> (/Users/stefan/Downloads/test/node_modules/why-is-node-running/index.js:50:6)
    at Module._compile (module.js:425:26)
FAIL: 1
```

Thanks.

Any hints are more than welcome. :bowtie:

**Comment by yoshuawuyts** [comment]
@stefanjudis what version of `node` / `npm` are you using?

**Comment by silverwind** [comment]
Also been hit by this, Node.js 5.7.0.

**Comment by johshoff** [comment]
Seeing this too. Node version 5.4.0 and both `why-is-node-running@1.1.2` and `why-is-node-running@1.2.1`

**Comment by voxpelli** [comment]
Experienced this as well on Node `5.6.0`, `5.0.0` but not on `4.2.1` – so it appears to be an incompatibility with Node 5

**Comment by voxpelli** [comment]
Probably related to https://github.com/nodejs/node/pull/3078

**Comment by wesleytodd** [comment]
Anyone find a resolution for this?  I can downgrade to 4 for a bit I guess, but if there is something simple we can do that would be great.  Thanks!

**Comment by silverwind** [comment]
Maybe try with `node --expose-internals script.js`.

**Comment by wesleytodd** [comment]
Worked!! Thanks!

**Comment by nolanlawson** [comment]
Downgrading to Node 4.2.3 worked for me.

**Comment by fresheneesz** [comment]
`--expose-internals` works for me on v5.1.0

**Comment by bojidar-bg** [comment]
Would be nice if this is done in the cli as well... :smile:

**Comment by Matthew-Davey** [comment]
--expose-internals works for me on v6.3.1

**Comment by mafintosh** [comment]
would be cool if we could add that switch to the cli somehow

**Comment by megakoresh** [comment]
Yes, I would like to have this switch in the cli options too.

**Comment by sibelius** [comment]
Can somebody document how to use with node 6 or node 8?

**Comment by silverwind** [comment]
I'm not sure if this is runtime-configurable, but can someone try adding

```
process.binding('config').exposeInternals = true
```

at the top of their script, and report back if that works?

**Comment by mafintosh** [comment]
oh interesting. I'll try later

**Comment by maksimioffe** [comment]
i am affected on v7.7.3, the `--expose-internals` workaround worked for me, but `process.binding('config').exposeInternals = true` did not

**Comment by silverwind** [comment]
Ah, that `exposeInternals` option does nothing as the variable is checked only earlier in the node bootstrap process, before any user script runs. I have a feeling this can only be solved by a change in node itself, but IIRC, internal modules are shielded from user code for a reason.

**Comment by mo** [comment]
I hit this today using node v7.7.2 and I'm using babel-node so --expose-internals doesn't work for me

**Comment by 4O4** [comment]
Too bad it's closed without clear solution. I've just hit the same wall 😞

**Comment by zixia** [comment]
I ran into this issue under node v8.6 with `--expose-internals `

```
There are 1 known handle(s) keeping the process running and 2 unknown
Known handles:

not ok 2 TypeError: Cannot read property 'indexOf' of null
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: Cannot read property 'indexOf' of null]
    stack: |-
      TypeError: Cannot read property 'indexOf' of null
          at /home/zixia/chatie/wechaty/node_modules/why-is-node-running/index.js:72:29
          at Array.filter (<anonymous>)
          at /home/zixia/chatie/wechaty/node_modules/why-is-node-running/index.js:71:21
          at Array.forEach (<anonymous>)
          at module.exports (/home/zixia/chatie/wechaty/node_modules/why-is-node-running/index.js:68:9)
```
